version: '3'
services:
  flask:
    build:
      context: .
      dockerfile: Dockerfile-flask
    ports:
      - "5000:5000"
    depends_on:
      - mongodb
      - engine
    environment:
      - MONGO_URI=mongodb://mongodb:27017/
  
  engine:
    build:
      context: .
      dockerfile: Dockerfile-engine
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
